apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-stats-url-configmap
data:
  URLS: "https://httpstat.us/503,https://httpstat.us/200"
  TIMEOUT: "2"
  PORT: "8080"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-stats-url-deploy
  labels:
    app: k8s-stats-url-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-stats-url
  template:
    metadata:
      labels:
        app: k8s-stats-url
    spec:
      containers:
      - name: k8s-stats-url
        image: <docker registry url>/k8s-stats-url
        env:
        - name: URLS
          valueFrom:
            configMapKeyRef:
              name: k8s-stats-url-configmap
              key: URLS
        - name: TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: k8s-stats-url-configmap
              key: TIMEOUT
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: k8s-stats-url-configmap
              key: PORT

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-stats-url-service
spec:
  type: LoadBalancer
  selector:
    app: k8s-stats-url
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
